### PR TITLE
Update subject.h

### PR DESCRIPTION
**Pull request by notabigthreat**

### CODE REVIEW

**Comment by notabigthreat** [comment]
@jab9k3 - does it work on your side after SFML is installed? Are there many repetetive warnings (that's what I'm trying to prevent) ?

**Comment by notabigthreat** [comment]
checked with my version of Visual, allright

**Comment by jab9k3** [comment]
i'll look at it ive had software training all month will be done soon have
examines next week so i'll check it out soon

**Comment by notabigthreat** [comment]
btw, what version is your visual?

**Comment by jab9k3** [comment]
i believe 2010

**Pull request merged**
